### ISSUE TITLE
Include links back to the relevant papers in the README file

### ISSUE THREAD

**Issue by goatchurchprime** [OmnesRes/infarction#1]
It's really useful to be able to find your way back starting from this page.

In this case it's https://peerj.com/preprints/3025/

PS.  I can't wait till you discover Jupyter.

**Comment by OmnesRes** [comment]
After the Retraction Watch article I was actually thinking about adding more documentation.  I have pointed people to jupyter when they tell me they want to run my code but don't know anything about Python, or programming.  I should probably learn how to set up a notebook some time.

**Comment by goatchurchprime** [comment]
Do it now.  It's inhumane to develop pylab/matplotlib scripts without it.  The necessary runes are:

from matplotlib import pyplot as plt
%matplotlib inline
